### ISSUE TITLE
SELinux issue: "cannot enable executable stack as shared object requires: Permission denied"

### ISSUE THREAD

**Issue by dfaggioli** [flathub/com.mattjakeman.ExtensionManager#2]
on openSUSE MicroOS (Desktop), if installed with SELinux enabled, the app does not start, and the following error is shown on the console:

`cannot enable executable stack as shared object requires: Permission denied
`
Which seemed SELinux related. in /var/log/audit/audit.log I see:

`type=AVC msg=audit(1643361322.448:108): avc: denied { execstack } for pid=2080 comm="extension-manag" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0`

I'm no SELinux expert, but I have a test system and can provide more information, if necessary, or run tests

**Comment by mjakeman** [comment]
Naively looking at the error message, I wonder if it's related to us bundling some shared libraries. We currently have newer versions of gtk4, libadwaita, and libsoup included inside the flatpak than are available in the GNOME 41 runtime.

There are a few other Flathub apps that also bundle libadwaita like this. Could you try installing these two and see if you can reproduce the error? If not, then it's definitely on our end.
 - https://flathub.org/apps/details/io.github.seadve.Kooha
 - https://flathub.org/apps/details/io.github.lainsce.Notejot

**Comment by dfaggioli** [comment]
> Naively looking at the error message, I wonder if it's related to us bundling some shared libraries. We currently have newer versions of gtk4, libadwaita, and libsoup included inside the flatpak than are available in the GNOME 41 runtime.
> 
> There are a few other Flathub apps that also bundle libadwaita like this. Could you try installing these two and see if you can reproduce the error? If not, then it's definitely on our end.
> 
>     * https://flathub.org/apps/details/io.github.seadve.Kooha
> 
>     * https://flathub.org/apps/details/io.github.lainsce.Notejot
>
Yep, seems the same issue (or at least the same symptoms):

```
$ flatpak run io.github.lainsce.Notejot 
io.github.lainsce.Notejot: error while loading shared libraries: libgtk-4.so.1: cannot enable executable stack as shared object requires: Permission denied
```

And in `/var/log/audit/audit.log`:
```
type=AVC msg=audit(1643361740.396:130): avc:  denied  { execstack } for  pid=2433 comm="io.github.lains" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0
```

**Comment by mjakeman** [comment]
Okay, that narrows it down a lot. Can you try installing the `gnome-nightly` version of the app?

You'll need the gnome-nightly runtime from [here](https://wiki.gnome.org/Apps/Nightly). Then install the flatpak binary from the [latest release](https://github.com/mjakeman/extension-manager/releases).

Since libadwaita and GTK 4.6 are part of the nightly runtime, this issue (hopefully) won't be present.

**Comment by syds-git** [comment]
For me that latest version works (running openSUSE MicroOS as well)

**Comment by mjakeman** [comment]
Great to hear.

I'm very unfamiliar with SELinux, so I'm not sure how to go about fixing this for the 'stable' flathub version.

We can safely assume this problem will go away when GNOME 42 (and associated flatpak runtime) launch in March this year. In the mean time, let's leave this issue open in case someone more familiar with SELinux policies can chime in. Otherwise, I would suggest using the nightly version of extension-manager instead until we can drop the bundled dependencies.

**Comment by mjakeman** [comment]
Hi @dfaggioli, I've released Extension Manager 0.3 (#8) using the GNOME 42 runtime, which should resolve the issue.

Can you confirm this is the case?

**Comment by teohhanhui** [comment]
I tried with the beta yesterday. It works (on openSUSE MicroOS Desktop with
SELinux in enforcing mode). So yes, I'd say this is resolved.

**Comment by mjakeman** [comment]
Great to hear.
